apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: my-source-connector
  labels:
    strimzi.io/cluster: my-connect-cluster
  namespace: debezium-demo
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    file: /opt/kafka/LICENSE
    topic: my-topic
    database.history.kafka.bootstrap.servers: 'my-cluster-kafka-bootstrap:9093'
    database.history.kafka.topic: schema-changes.inventory
    database.hostname: spring-music-db
    database.port: 3306
    database.user: "${file:/opt/kafka/external-configuration/connector-config/debezium-mysql-credentials.properties:mysql_username}"
    database.password: "${file:/opt/kafka/external-configuration/connector-config/debezium-mysql-credentials.properties:mysql_password}"
    database.dbname: music
    database.server.name: demo_connector_mysql
