apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: mysql-source-connector
  labels:
    strimzi.io/cluster: my-source-connect-cluster
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    database.server.name: mysql-inventory
    database.hostname: mysql
    database.password: <your password>
    database.port: '3306'
    database.whitelist: inventory
    database.history.kafka.topic: schema-changes.inventory
    database.history.kafka.bootstrap.servers: 'my-cluster-kafka-bootstrap:9092'
    database.dbname: inventory
    database.user: debezium
    transforms: unwrap
    transforms.unwrap.delete.handling.mode: rewrite
    transforms.unwrap.drop.tombstones: false
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.add.fields: op,table,db,source.ts_ms,source.db
    key.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
