apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  annotations:
    strimzi.io/use-connector-resources: 'true'
  name: 'my-connect-cluster'
spec:
  bootstrapServers: 'my-cluster-kafka-bootstrap:9092'
  config:
    config.storage.topic: 'debezium-cluster-configs'
    group.id: 'debezium-cluster'
    offset.storage.topic: 'debezium-cluster-offsets'
    status.storage.topic: 'debezium-cluster-status'
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
  image: 'quay.io/redhatintegration/rhi-cdc-connect:2021-Q1'
  jvmOptions:
    gcLoggingEnabled: false
  replicas: 1
  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 1Gi
